planilla/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url('^$', Inicio.as_view(), name='home'),
    # Inician urls para Estado Civil
    url(r'^agregar_estadocivil/', AgregarEstadoCivil.as_view(), name='agregar_estadocivil'),
    url(r'^estadosciviles/$', estadosciviles, name='estadosciviles'),
    url(r'^actualizar_estadocivil/(?P<pk>\d+)$', ActualizarEstadoCivil.as_view(), name='actualizar_estadocivil'),
    url(r'^desactivar_estadocivil/(?P<pk>\d+)$', desactivar_estadocivil, name='desactivar_estadocivil'),
    # Finalizan urls para Estado Civil

    #Inician urls para Estructura Territorial
    url(r'^estructura_territorial/$', Estructura_territorial, name="estructuras"),
    url(r'^estructura_territorial/ajax/obtener_divisiones/$', obtener_division, name='obtener_divisiones'),
    url(r'^estructura_territorial/ajax/guardar_division/$', guardar_division, name='guardar_division'),
    url(r'^estructura_territorial/ajax/eliminar_division/$', eliminar_division, name='eliminar_division'),
    #Finalizan urls para Estructura Territorial

    # Inician urls para Profesión
    url(r'^agregar_profesion/', AgregarProfesion.as_view(), name='agregar_profesion'),
    url(r'^profesiones/$', profesiones, name='profesiones'),
    url(r'^actualizar_profesion/(?P<pk>\d+)$', ActualizarProfesion.as_view(), name='actualizar_profesion'),
    url(r'^desactivar_profesion/(?P<pk>\d+)$', desactivar_profesion, name='desactivar_profesion'),
    # Finalizan urls para Profesión

    # Inician urls para Comisiones
    url(r'^agregar_comision/', AgregarComision.as_view(), name='agregar_comision'),
    url(r'^agregar_comisiones/$', AgregarComisiones, name='agregar_comisiones'),
    url(r'^actualizar_comisiones/(?P<pk>\d+)$', ActualizarComisiones, name='actualizar_comisiones'),
    url(r'^eliminar_comisiones/(?P<pk>\d+)/(?P<hasta>\d+\.\d{2})$', eliminar_comisiones, name='eliminar_comisiones'),
    url(r'^comisiones/$', comisiones, name='comisiones'),
    url(r'^actualizar_comision/(?P<pk>\d+)$', ActualizarComision.as_view(), name='actualizar_comision'),
    url(r'^eliminar_comision/(?P<pk>\d+)$', eliminar_comision, name='eliminar_comision'),
    # Finalizan urls para Comisiones

    # Inician urls para Tipos de Ingreso
    url(r'^agregar_tipoingreso/', AgregarTipoIngreso.as_view(), name='agregar_tipoingreso'),
    url(r'^ingresos/$', ingresos, name='ingresos'),
    url(r'^actualizar_tipoingreso/(?P<pk>\d+)$', ActualizarTipoIngreso.as_view(), name='actualizar_tipoingreso'),
    url(r'^desactivar_tipoingreso/(?P<pk>\d+)$', desactivar_tipoingreso, name='desactivar_tipoingreso'),
    # Finalizan urls para Tipos de Ingreso

    # Inician urls para Género
    url(r'^agregar_genero/', AgregarGenero.as_view(), name='agregar_genero'),
    url(r'^generos/$', generos, name='generos'),
    url(r'^actualizar_genero/(?P<pk>\d+)$', ActualizarGenero.as_view(), name='actualizar_genero'),
    url(r'^desactivar_genero/(?P<pk>\d+)$', desactivar_genero, name='desactivar_genero'),
    # Finalizan urls para Género

    # Inician urls para Empleado
    url(r'^agregar_empleado/', AgregarEmpleado.as_view(), name='agregar_empleado'),
    url(r'^empleados/$', empleados, name='empleados'),
    url(r'^subordinados/(?P<id>\d+)$', subordinados, name='subordinados'),
    url(r'^actualizar_empleado/(?P<pk>\d+)$', ActualizarEmpleado.as_view(), name='actualizar_empleado'),
    url(r'^desactivar_empleado/(?P<pk>\d+)$', desactivar_empleado, name='desactivar_empleado'),
    # Finalizan urls para Empleado

    # Inician urls para Descuento
    url(r'^agregar_descuento/', AgregarDescuento.as_view(), name='agregar_descuento'),
    url(r'^descuentos/$', descuentos, name='descuentos'),
    url(r'^actualizar_descuento/(?P<pk>\d+)$', ActualizarDescuento.as_view(), name='actualizar_descuento'),
    url(r'^desactivar_descuento/(?P<pk>\d+)$', desactivar_descuento, name='desactivar_descuento'),
    # Finalizan urls para Descuento

    # Inician urls para Cotización
    url(r'^agregar_cotizacion/', AgregarCotizacion.as_view(), name='agregar_cotizacion'),
    url(r'^cotizaciones/$', cotizaciones, name='cotizaciones'),
    url(r'^actualizar_cotizacion/(?P<pk>\d+)$', ActualizarCotizacion.as_view(), name='actualizar_cotizacion'),
    url(r'^desactivar_cotizacion/(?P<pk>\d+)$', desactivar_cotizacion, name='desactivar_cotizacion'),
    # Finalizan urls para Cotización

    # Inician urls para Cotización
    url(r'^actualizar_empresa/', actualizar_empresa, name='actualizar_empresa'),
    # Finalizan urls para Cotización

    # Inician urls para Renta
    url(r'^agregar_escala/$', AgregarEscala, name='agregar_escala'),
    url(r'^escalas/$', escalas, name='escalas'),
    url(r'^actualizar_escala/(?P<pk>\d+)$', ActualizarEscala, name='actualizar_escala'),
    url(r'^eliminar_escala/(?P<pk>\d+)/(?P<hasta>\d+\.\d{2})$', eliminar_tramos, name='eliminar_escala'),
    # Finalizan urls para Renta

    # Inicia urls para Unidades Organizacionales
    url(r'^agregar_unidad_organizacional/$', AgregarUnidadOrganizacional.as_view(), name='agregar_unidad_organizacional'),
    url(r'^unidades/$', unidades, name='unidades'),
    url(r'^actualizar_unidadorganizacional/(?P<pk>\d+)$', ActualizarUnidadOrganizacional.as_view(), name='actualizar_unidadorganizacional'),
    url(r'^desactivar_unidad/(?P<pk>\d+)$', desactivar_unidad, name='desactivar_unidad'),
    # Finalizan urls para Unidades Organizacionales

    #Inicia urls para Calendario
    url(r'^agregar_calendario/', agregar_calendario, name='agregar_calendario'),
    url(r'^calendarios/$', calendarios,name='calendarios_anuales'),
    #Finaliza urls para Calendario

    #Inicial urls para Presupuesto
    url(r'^agregar_presupuesto/', AgregarPresupuesto.as_view(), name='agregar_presupuesto'),
    url(r'^presupuestos/$', presupuestos, name='presupuestos'),
    url(r'^actualizar_presupuesto/(?P<pk>\d+)$', ActualizarPresupuesto.as_view(), name='actualizar_presupuesto'),
    #Finalizan urls para Presupuesto

    # Inician urls para Puesto de Trabajo
    url(r'^agregar_puesto/', AgregarPuesto.as_view(), name='agregar_puesto'),
    url(r'^puesto_trabajo/$', puestos, name='puestos'),
    url(r'^actualizar_puesto/(?P<pk>\d+)$', ActualizarPuesto.as_view(), name='actualizar_puesto'),
    url(r'^desactivar_puesto/(?P<pk>\d+)$', desactivar_puesto, name='desactivar_puesto'),
    # Finalizan urls para Puesto de Trabajo

    #Inicial urls para Planilla
    url(r'^planilla/$',ver_planilla, name='ver_planilla'),
    url(r'^planilla/guardar_ingresos/$',guardar_ingresos, name='guardar_ingreso'),
    url(r'^planilla/guardar_descuentos/$', guardar_descuentos, name='guardar_descuento'),
    url(r'^planilla/guardar_comisiones/$', guardar_comisiones, name='guardar_comisiones'),
    url(r'^planilla/obtener_montos/$', obtener_montos, name='obtener_montos'),
    url(r'^planilla/cerrar_planilla/$', cerrar_planilla, name='cerrar_planilla'),
    url(r'^planilla/imprimir_boleta/$', ImprimirBoletaPDFView.as_view(), name='imprimir_boleta'),
    #Finalizan urls para Planilla
]

si_planilla/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('planilla.urls')),
    url(r'^', include('autenticacion.urls')),
    url(r'^admin/', admin.site.urls),
]

planilla/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.postgres.fields import ArrayField

# Create your models here.
CHOICES = (
    ('1', 'Quincenal'),
    ('2', 'Mensual'),
)

class PlanillaAnual(models.Model):
    año = models.IntegerField('Año', blank=False, null=False, unique=True)
    periocidad_pago = models.CharField('Periocidad de pago', max_length=50, blank=False, null=False)
    devengada = models.BooleanField('¿Está devengada?', default=False)

    def __str__(self):
        return 'Planilla para el año: - %s' % (self.año.__str__())

    class Meta:
        verbose_name = 'PlanillaAnual'
        verbose_name_plural = 'PlanillasAnuales'

class EstadoCivil(models.Model):
    nombre = models.CharField('Nombre', max_length = 64, unique = True)
    activo = models.BooleanField('¿Activo?', default=True)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Estado Civil'
        verbose_name_plural = 'Estados Civiles'

class Profesion(models.Model):
    nombre = models.CharField('Nombre', max_length = 64, unique = True)
    activo = models.BooleanField('¿Activo?', default=True)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Profesión'
        verbose_name_plural = 'Profesiones'

class Genero(models.Model):
    nombre = models.CharField('Nombre', max_length = 64, unique=True)
    activo = models.BooleanField('¿Activo?', default=True)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Género'
        verbose_name_plural = 'Géneros'

class Renta(models.Model):
    tipo = models.CharField('Tipo', max_length = 1, choices = CHOICES, blank = False, null = False, default = ('1'))
    desde = models.DecimalField('Desde', max_digits=8, decimal_places=2, blank=False, null=False, validators = [MinValueValidator(0)])
    hasta = models.DecimalField('Hasta', max_digits=8, decimal_places=2, blank=False, null=False, validators = [MinValueValidator(0)])
    porcentaje = models.DecimalField('Porcentaje a aplicar', max_digits=5, decimal_places=2, blank=True, null=True, validators = [MinValueValidator(0), MaxValueValidator(100.00)])
    exceso = models.DecimalField('Sobre el exceso de', max_digits=8, decimal_places=2, blank=True, null=True, validators = [MinValueValidator(0)])
    cuota_fija = models.DecimalField('Más cuota fija de', max_digits=8, decimal_places=2, blank=True, null=True, validators = [MinValueValidator(0)])

    def __str__(self):
        return 'Tramo de Renta: %.2f - %.2f' % (self.desde, self.hasta)

    def get_tipo_display(self):
        for tipo in CHOICES:
            if self.tipo == tipo[0]:
                return tipo[1]

    class Meta:
        unique_together = (('tipo', 'desde',), ('tipo', 'hasta',))
        verbose_name ='Tabla de Renta'
        verbose_name_plural = 'Tramos de Tabla de Renta'

class Comision(models.Model):
    lim_inferior = models.DecimalField('Límite Inferior', max_digits=8, decimal_places=2, blank=False, null=False, validators=[MinValueValidator(0)])
    lim_superior = models.DecimalField('Límite Superior', max_digits=8, decimal_places=2, blank=False, null=False, validators=[MinValueValidator(0)])
    porcentaje = models.DecimalField('Tasa de Comisión', max_digits=5, decimal_places=2, blank=False, null=False, validators=[MinValueValidator(0), MaxValueValidator(100.00)])

    def __str__(self):
        return 'Tasa de Comisión: %f - %f' % (self.lim_inferior, self.lim_superior)

    class Meta:
        verbose_name = 'Tasa de Comisión'
        verbose_name_plural = 'Tasas de Comisión'

class UnidadOrganizacional(models.Model):
    nombre = models.CharField('Nombre', max_length=128, unique=True)
    activo = models.BooleanField('¿Unidad Organizacional Activa?', default=True)
    superseccion = models.ForeignKey('self', null=True, blank=True, related_name='subsecciones')

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Unidad Organizacional'
        verbose_name_plural = 'Unidades Organizacionales'

class Calendario(models.Model):
    anio = models.IntegerField('Año', blank=False, null=False, unique=False)
    fecha_pago = models.DateField('Fecha de Pago', blank=False, null=False)
    activo = models.BooleanField('¿Calendario Activo?', default=True)
    planilla_anual = models.ForeignKey(PlanillaAnual, null=False, default=1)

    def __str__(self):
        return str(self.anio)

    def get_periodicidad_display(self):
        for periodicidad in CHOICES:
            if self.periodicidad == periodicidad[0]:
                return periodicidad[1]

    class Meta:
        verbose_name = 'Calendario'
        verbose_name_plural = 'Calendarios'

class DiaInvalido(models.Model):
    dia = models.DateField('Día', blank=False, null=False)

    def __str__(self):
        return self.dia

    class Meta:
        verbose_name = 'Día Inválido'
        verbose_name_plural = 'Días Inválidos'

class Presupuesto(models.Model):
    monto_inicial = models.DecimalField('Monto Inicial', max_digits=8, decimal_places=2, blank=False, null=False, validators=[MinValueValidator(0)])
    monto_disponible = models.DecimalField('Monto Disponible', max_digits=8, decimal_places=2, blank=False, null=False, validators=[MinValueValidator(0)])

    planilla_anual = models.ForeignKey(PlanillaAnual, null=False)
    unidad_organizacional = models.ForeignKey(UnidadOrganizacional, null=False)

    def __str__(self):
        return 'Presupuesto de %s para el año %s' % (self.unidad_organizacional, self.planilla_anual.año.__str__())

    class Meta:
        # Una Unidad Organizacional no puede tener más de un presupuesto para un mismo año
        unique_together = ('planilla_anual', 'unidad_organizacional',)
        verbose_name = 'Presupuesto'
        verbose_name_plural = 'Presupuestos'

class PuestoTrabajo(models.Model):
    nombre = models.CharField('Nombre', max_length=64, unique=True)
    activo = models.BooleanField('¿Puesto de Trabajo Activo?', default=True)
    salario_min = models.DecimalField('Salario Mínimo', max_digits=8, decimal_places=2, blank=False, null=False,validators=[MinValueValidator(0)])
    salario_max = models.DecimalField('Salario Máximo', max_digits=8, decimal_places=2, blank=False, null=False,validators=[MinValueValidator(0)])

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Puesto de Trabajo'
        verbose_name_plural = 'Puestos de Trabajo'

class EstructuraTerritorial(models.Model):
    nombre = models.CharField('Nombre', max_length=128)
    superdivision = models.ForeignKey('self', null=True, blank=True, related_name='subdivisiones')

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Estructura Territorial'
        verbose_name_plural = 'Estructuras Territoriales'


class Empleado(models.Model):
    primer_nombre = models.CharField('Primer nombre', max_length=32, null=False)
    segundo_nombre = models.CharField('Segundo nombre', max_length=32, blank=True, null=True)
    apellido_paterno = models.CharField('Apellido paterno', max_length=32, blank=True, null=True)
    apellido_materno = models.CharField('Apellido materno', max_length=32, blank=True, null=True)
    apellido_casada = models.CharField('Apellido casada', max_length=32, blank=True, null=True)

    dui = models.CharField('Número de DUI', max_length=10, help_text='Formato: XXXXXXXX-X', unique=True)
    nit = models.CharField('Número de NIT', max_length=17, help_text='Formato: XXXX-XXXXXX-XXX-X', unique=True)
    nup = models.CharField('Número de NUP', max_length=12, unique=True)
    isss = models.CharField('Número de ISSS', max_length=7, unique=True)
    pasaporte = models.CharField('Número de Pasaporte', max_length=9, unique=True, blank=True)

    fecha_nacimiento = models.DateField('Fecha de nacimiento', help_text='Formato: DD/MM/AAAA')
    fecha_ingreso = models.DateField('Fecha de ingreso', help_text='Formato: DD/MM/AAAA')

    telefono = models.CharField('Número de teléfono', max_length = 9, help_text='Formato: XXXX-XXXX',unique=True)
    email_personal = models.EmailField('Correo Electrónico Personal', max_length=256, unique=True)
    email_institucional = models.EmailField('Correo Electrónico Institucional', max_length=256, unique=True)
    direccion = models.CharField('Dirección', max_length = 64, help_text='Dirección de su residencia')
    domicilio = models.ForeignKey(EstructuraTerritorial, null=False, blank=False)

    activo = models.BooleanField('¿Empleado Activo?', default = True)
    salario_fijo = models.CharField('Tipo de Puesto', max_length = 1, default='1', choices=(('1', 'Salario Fijo'),('2', 'Salario por Comisión'),))


    genero = models.ForeignKey(Genero, null = False)
    estado_civil = models.ForeignKey(EstadoCivil, null = False)
    jefe = models.ForeignKey('self', null = True, related_name = 'subordinados', blank = True)
    puesto = models.ForeignKey(PuestoTrabajo, null = False, blank = False)
    profesion = models.ForeignKey(Profesion, null=True, blank=True)
    unidad_organizacional = models.ForeignKey(UnidadOrganizacional, null=False, default=1)
    salario = models.DecimalField('Salario', max_digits=8, decimal_places=2, blank=False, null=False,validators=[MinValueValidator(0)])

    def __str__(self):
        nombre = self.primer_nombre.title()
        if self.segundo_nombre:
            nombre += " " + self.segundo_nombre.title()
        if self.apellido_paterno:
            nombre += " " + self.apellido_paterno.title()
        if self.apellido_casada:
            nombre += "de" + self.apellido_casada.title()
        else:
            nombre += " " + self.apellido_materno.title()
        return nombre

    class Meta:
        ordering = ['primer_nombre']
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados'

class Empresa(models.Model):

planilla/templates/planilla/empleados.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="col s12">
        <h5>Consulta de Empleados:</h5>
    </div>
    <div class="consulta-tabla">
        <table class="table table-striped table-bordered table-hover" data-toggle="bootgrid" id="planilla_table">
            <thead>
            <tr>
                <th>Nombre del empleado</th>
                <th>DUI</th>
                <th>Jefe</th>
                <th>Puesto</th>
                <th>Subordinados</th>
                <th>Gestionar</th>
                <th>¿Activo?</th>
            </tr>
            </thead>
            <tbody>
            {% for empleado in empleados %}
                <tr>
                    <td>{{empleado.primer_nombre}}</td>
                    <td>{{empleado.dui}}</td>
                    <td>{{empleado.jefe.primer_nombre}}</td>
                    <td>{{empleado.puesto.nombre}}</td>
                    <td> <a class="btn btn-primary waves-effect waves-light" href="{% url 'subordinados' id=empleado.id %}">
                                <i class="material-icons">group</i>
                            </a> </td>
                    {% if perms.planilla.change_empleado%}
                        <td>
                            <a class="btn btn-primary waves-effect waves-light" href="{% url 'actualizar_empleado' pk=empleado.id %}">
                                <i class="material-icons">edit</i>
                            </a>
                        </td>
                    {% endif %}
                    {% if perms.planilla.delete_empleado%}
                        {% if empleado.activo %}
                            <td><a class="btn btn-active waves-effect waves-light" onclick="Eliminar{{ empleado.id }}()"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></a></td>
                        {% elif not empleado.activo %}
                            <td><a class="btn btn-danger waves-effect waves-light" onclick="Eliminar{{ empleado.id }}()"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></td>
                        {% endif %}
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% for empleado in empleados %}
        <script type="text/javascript">
            function Eliminar{{ empleado.id }}(){
                swal({   title: "¡Se modificará el estado del empleado: {{ empleado.nombre }}!",
                        text: "¿Está seguro que desea continuar?",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "Sí, deseo continuar",
                        cancelButtonText: "No, no estoy seguro",
                        closeOnConfirm: false,
                        closeOnCancel: false },
                    function(isConfirm){
                        if (isConfirm)
                        {
                            window.location.href = '{% url 'desactivar_empleado' pk=empleado.id %}';
                        }
                        else {
                            swal("Cancelar", "¡Se canceló la operación!", "error");
                        } });
            }
        </script>
    {% endfor %}
{%endblock%}

planilla/templates/planilla/estados.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="col s12">
        <h5>Consulta de Estados Civiles:</h5>
    </div>
    <div class="consulta-tabla">
        <table class="table table-striped table-bordered table-hover" data-toggle="bootgrid" id="planilla_table">
            <thead>
            <tr>
                <th>Nombre del Estado Civil</th>
                <th>Gestionar</th>
                <th>¿Activo?</th>
            </tr>
            </thead>
            <tbody>
            {% for estado in estados %}
                <tr>
                    <td>{{estado.nombre}}</td>
                    {% if perms.planilla.change_estadocivil%}
                        <td>
                            <a class="btn btn-primary waves-effect waves-light" href="{% url 'actualizar_estadocivil' pk=estado.id %}">
                                <i class="material-icons">edit</i>
                            </a>
                        </td>
                    {% endif %}
                    {% if perms.planilla.delete_estadocivil%}
                        {% if estado.activo %}
                            <td><a class="btn btn-active waves-effect waves-light" onclick="Eliminar{{ estado.id }}()"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></a></td>
                        {% elif not estado.activo %}
                            <td><a class="btn btn-danger waves-effect waves-light" onclick="Eliminar{{ estado.id }}()"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></td>

                        {% endif %}


                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% for estado in estados %}
        <script type="text/javascript">
            function Eliminar{{ estado.id }}(){
                swal({   title: "¡Se Modificará la Condición del Estado Civil {{ estado.nombre }}!",
                        text: "¿Está seguro que desea continuar?",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "Sí, deseo continuar",
                        cancelButtonText: "No, no estoy seguro",
                        closeOnConfirm: false,
                        closeOnCancel: false },
                    function(isConfirm){
                        if (isConfirm)
                        {
                            window.location.href = '{% url 'desactivar_estadocivil' pk=estado.id %}';
                        }
                        else {
                            swal("Cancelar", "¡Se canceló la operación!", "error");
                        } });
            }
        </script>
    {% endfor %}
{%endblock%}

planilla/templates/planilla/presupuestos.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="col s12">
        <h5>Consulta de Presupuestos:</h5>
    </div>
    <div class="consulta-tabla">
        <table class="table table-striped table-bordered table-hover" data-toggle="bootgrid" id="planilla_table">
            <thead>
            <tr>
                <th>Monto Inicial</th>
                <th>Monto Disponible</th>
                <th>Unidad Organizacional</th>
                <th>Periodo</th>
                <th>Gestionar</th>
            </tr>
            </thead>
            <tbody>
            {% for presupuesto in presupuestos %}
                <tr>
                    <td>{{presupuesto.monto_inicial}}</td>
                    <td>{{presupuesto.monto_disponible}}</td>
                    <td>{{presupuesto.unidad_organizacional}}</td>
                    <td>{{presupuesto.planilla_anual.año}}</td>
                    {% if perms.planilla.change_presupuesto%}
                        {% if presupuesto.monto_inicial == presupuesto.monto_disponible %}
                            <td>
                                <a class="btn btn-primary waves-effect waves-light" href="{% url 'actualizar_presupuesto' pk=presupuesto.id %}">
                                    <i class="material-icons">edit</i>
                                </a>
                            </td>
                            {% else %}
                            <td>N/A</td>
                        {% endif %}
                    {% endif %}

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{%endblock%}

planilla/templates/planilla/unidades.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="col s12">
        <h5>Consulta de Unidades Organizacionales de la Empresa:</h5>
    </div>
    <div class="consulta-tabla">
        <table class="table table-striped table-bordered table-hover" data-toggle="bootgrid" id="planilla_table">
            <thead>
            <tr>
                <th>Nombre de la Seccion</th>
                <th>Nombre de la Super-Seccion</th>
                <th>Gestionar</th>
                <th>¿Activo?</th>
            </tr>
            </thead>
            <tbody>
            {% for unidad in unidades %}
                <tr>
                    <td>{{unidad.nombre}}</td>
                    <td>{{unidad.superseccion}}</td>
                    {% if perms.planilla.change_unidadorganizacional%}
                        <td>
                            <a class="btn btn-primary waves-effect waves-light" href="{% url 'actualizar_unidadorganizacional' pk=unidad.id %}">
                                <i class="material-icons">edit</i>
                            </a>
                        </td>
                    {% endif %}
                    {% if perms.planilla.delete_unidadorganizacional%}
                        {% if unidad.activo %}
                            <td><a class="btn btn-active waves-effect waves-light" onclick="Eliminar{{ unidad.id }}()"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></a></td>
                        {% elif not unidad.activo %}
                            <td><a class="btn btn-danger waves-effect waves-light" onclick="Eliminar{{ unidad.id }}()"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></td>

                        {% endif %}


                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% for unidad in unidades %}
        <script type="text/javascript">
            function Eliminar{{ unidad.id }}(){
                swal({   title: "¡Se Modificará el Estado de la Unidad Organizacional {{ unidad.nombre }}!",
                        text: "¿Está seguro que desea continuar?",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "Sí, deseo continuar",
                        cancelButtonText: "No, no estoy seguro",
                        closeOnConfirm: false,
                        closeOnCancel: false },
                    function(isConfirm){
                        if (isConfirm)
                        {
                            window.location.href = '{% url 'desactivar_unidad' pk=unidad.id %}';
                        }
                        else {
                            swal("Cancelar", "¡Se canceló la operación!", "error");
                        } });
            }
        </script>
    {% endfor %}
{%endblock%}